### ISSUE TITLE
Spoke template needs update for v3.0.0

### ISSUE THREAD

**Issue by henkler** [awslabs/aws-centralized-logging#15]
https://github.com/awslabs/aws-centralized-logging/blob/2a396e4633e07fccafb1937ed7564dca5c2b1120/deployment/centralized-logging-spoke.template#L135

It looks like the spoke template didn't get updated to v3.0.0, and breaks when deploying against the main v3.0.0 template.

The fix looks fairly simple, just update the environment variables to match the main template.

```
  LogStreamer:
    Type: AWS::Lambda::Function
    Properties:
      Description: Centralized Logging - Lambda function to stream logs cross account on ES Domain
      Environment:
        Variables:
          # V56536055 - 10/08/2018 - better logging capabilities
          LOG_LEVEL: 'INFO' #change to WARN, ERROR or DEBUG as needed
          DOMAIN_ENDPOINT: !Sub ${ESDomain}
          MASTER_ROLE: !Sub ${MasterRole}
          SESSION_ID: !Sub ${AWS::AccountId}-${AWS::Region}
          OWNER: Spoke
          SOLUTION: SO0009s
          CLUSTER_SIZE: !Ref ClusterSize
          UUID: !Sub ${CreateUniqueID.UUID}
          ANONYMOUS_DATA: !FindInMap [InstanceMap, send-data, SendAnonymousData]
      Handler: index.handler
      Role: !Sub ${LogStreamerRole.Arn}
      Code:
        S3Bucket: !Join ["-", [!FindInMap ["SourceCode", "General", "S3Bucket"], Ref: "AWS::Region"]]
        S3Key: !Join ["/", [!FindInMap ["SourceCode", "General", "KeyPrefix"],  "clog-indexing-service.zip"]]
      Runtime: nodejs8.10
      Timeout: 300
```
